### ISSUE TITLE
Doesn't seem to work currently

### ISSUE THREAD

**Issue by lyssieth** [ShayBox/MultiMC-Twitch#1]
```
CommandLineError: Unknown Option --import
Try '%1 -h' to get help on MultiMC's command line parameters.
exit status 1
```
I get this when trying to use MultiMC-Twitch to import a modpack (MC Eternal).
OS: Arch Linux
MultiMC Version: Version 0.6.8-custom Git `22d2a3bdf9b100fc1d75ff7ea010581a312eab5b`

**Comment by ShayBox** [comment]
You have to use the git version, stable stupidly released before merging
the import flag but after removing all support for twitch urls

**Comment by lyssieth** [comment]
Ah, thank you.
