### ISSUE TITLE
old api got deprecated some weeks ago

### ISSUE THREAD

**Issue by DioEgizio** [ShayBox/MultiMC-Twitch#12]
this still uses the deprecated curseforge api that doesn't work anymore

https://github.com/ShayBox/PolyMC-Curseforge/blob/b9d88e9066a1c4e7a7fbe2c4e649d619f1bc270d/main.go#L137

**Comment by ShayBox** [comment]
Unfortunately their new API doesn't appear to have the required endpoints for PolyMC-Curseforge to function, additionally their new API requires authentication and approval for access.

**Comment by ShayBox** [comment]
Their API has been updated with the required endpoints and no longer requires approval for access.  
I've rewrote the program in Rust and tested it on Windows, macOS, and Linux.
