### ISSUE TITLE
No longer seems to work due to the latest change from the Twitch app to the Curse app.

### ISSUE THREAD

**Issue by OldGitCorn** [ShayBox/MultiMC-Twitch#3]
Title says it all really, the `curseforge://` protocol seems to not work with this.

**Comment by ShayBox** [comment]
Wow, that partnership didn't last long, I'll make appropriate changes to the project soon, including a rename to MultiMC-Curseforge

**Comment by ShayBox** [comment]
Changes have been made and a release has been published
