### ISSUE TITLE
Just, doesn't work?

### ISSUE THREAD

**Issue by OldGitCorn** [ShayBox/MultiMC-Twitch#4]
When clicking the curseforge install button nothing happens, when running `multimc-curseforge <link>`, it throws the below error
`panic: runtime error: index out of range [3] with length 1`

`goroutine 1 [running]:`
`main.main()`
`	/home/shaybox/Documents/Go/MultiMC-Curseforge/main.go:35 +0x2f9`

**Comment by ShayBox** [comment]
Fixed in #cae9723
