### ISSUE TITLE
Can't seem to get it working

### ISSUE THREAD

**Issue by tomaskallup** [ShayBox/MultiMC-Twitch#5]
Hello, I can't seem to get this working properly. I installed `multimc-git` and `multimc-curseforge` from the AUR, but when I visit a modpack page on curseforge, the install button send me to download cursforge client. Is there some extra step I need to take? I would also be okay with somehow creating the `curseforge://` link, but I have no idea how they are constructed.
Bellow is an image with the link of the `Install` button on curseforge.
![image](https://user-images.githubusercontent.com/26621166/109398124-fd51e980-793a-11eb-90d6-1dcf2d50c905.png)

**Comment by ShayBox** [comment]
Everything is correct, clicking thst button should prompt with a pop-up of which application to handle the custom protocol, if that's not happening try using a different browser, it might be a problem with the browser.

**Comment by tomaskallup** [comment]
I have tried Firefox, Firefox in private window and Google Chrome (I have no addons in Chrome), but got the same result.

**Comment by ShayBox** [comment]
What desktop environment are you using, maybe it's not recognizing the protocol option in the desktop file

**Comment by tomaskallup** [comment]
I'm not using a desktop environment. Maybe I need to import the file handler manualy?

**Comment by ShayBox** [comment]
You need xdg-open installed to handle protocols
