### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by ItsErikSquared** [ShayBox/MultiMC-Twitch#7]
Windows defender flagged this as a virus:
![image](https://user-images.githubusercontent.com/24434408/119606799-2f031100-bdc1-11eb-80aa-050916f83f43.png)

I ran it through VirusTotal which it got a 6/69 so I mean that seems safe:
https://www.virustotal.com/gui/file/ba42acc7fd5d553a940f86b02612e90cf63c77b8ca34a037ea68695756bb419f/detection

I don't know if it is just the fact that it changes registry values that it triggers it.

Just a heads up to others.

**Comment by ShayBox** [comment]
I don't know what triggers the detections, maybe registry editing, maybe because there's a few generic copy pasted functions, but it's safe, the source code is public and you can compile your own to verify, it would probably still get detected.
